Historia
--------
This is a small generic sequence container with which to keep track of a list of elements, that
supports bi-directional traversal with access only to the previous, current, next, and first/last elements, where
insertion results in deletion of all tail element(s). Another way to think of it, is a train wherein a person 
inside a freight car may disconnect any freight cars behind the one they are currently in, or add one to the end. Also, if attempting to 
add an element, if the data is identical to the current element, nothing will be added. Use cases for this are, for 
example, to keep a history of a browser's pages using its forward/backward buttons.

   OO O o o o...      ______________________ _________________ ___________________
  O     ____          |                    | |       o         | |               |
 ][_n_i_| (   ooo___  |                    | |      /|\        | |               |
(__________|_[______]_|____________________|_|______/\_________|_|_______________|
0--0--0      0  0      0       0     0        0        0

What this IS:

* An idiomatic wrapper around a deque
* A generic templated container
* A header-only library
* Insular, and should never throw exceptions or have error states unless from the standard library methods

This is NOT:

* A perfomant implementation
* A featureful library. This solves a very specific use-case
 
 
 
==== Example
[source,ruby]
----
Historia<std::string> historia; //Create our class object
historia.push("Test string"); //Push data into our object
std::cout << historia.current(); //Will return and print our current string "Test String"
----


==== CMake integration
To use this library you may simply download it and include it your project, or download it via your package manager. To use it with CMake, you may use the example(s) below...
[source,cmake]
----
include(FetchContent)

FetchContent_Declare(
    historia
    GIT_REPOSITORY https://github.com/TechnicFully/Historia
    GIT_TAG        main
    GIT_SHALLOW    true
)
FetchContent_MakeAvailable(historia)

target_link_libraries(your_target PRIVATE Historia::historia) # Replace your_target with your CMake target
----

If you would rather directly download the file without using FetchContent, you can simply use this

[source,cmake]
----
if (NOT EXISTS historia.hpp)
	  file(DOWNLOAD https://raw.githubusercontent.com/technicfully/historia/master/historia.hpp historia.hpp)
endif()
----
 

==== Methods
[width="190%",cols="4,3,3,3"]
|=========================================================
|Return value |Method name | Parameters | Throws exception
|void |push() | T data | No
|std::optional<T> | current() | None | Yes
|std::optional<T> | next() | None | No
|std::optional<T> | previous() | None | No
|std::optional<T> | first() | None | Yes
|std::optional<T> | last() | None | Yes
|constexpr auto | max_size() | None | No
|auto | size() | None | No
|=========================================================

The primary function is _push()_. This is used to add data, or 'pages'. _next()_ and _previous()_ are to access each item without modifying the list, and will be the secondarily most used functions. _first()_ and _last()_ are to access the head and tail elements respectively if needed. _size()_ returns the number of elements currently in the list, and _max_size()_ returns the maximum number of elements, which by default is a 8 bit value (256 possible values). This can by changed by editing _History_stack<uint8_t> history_stack;_ in history.hpp to a different variable type if needed. In the event that data is _push()_'d when at capacity, the head element will be removed.

current(), next(), previous(), first(), and last() all return the accessed item if available, otherwise they will return std::nullopt.


